// Generated by LiveScript 1.3.1
(function(){
  var socket;
  socket = function(app){
    var io, connectedUser, completedUser;
    io = require('socket.io')(app);
    connectedUser = [];
    completedUser = [];
    return io.on('connection', function(socket){
      var refreshCount;
      console.log(io.sockets.sockets.length + ' users');
      refreshCount = function(){
        return io.emit('refresh', completedUser.length);
      };
      socket.on('completion', function(userName){
        console.log(completedUser);
        if (in$(userName, completedUser)) {
          console.log(userName + ' already connect');
        } else {
          completedUser.push(userName);
          console.log('completion');
        }
        return refreshCount();
      });
      return socket.on('disconnect', function(){
        return console.log('disconnect');
      });
    });
  };
  module.exports = socket;
  function in$(x, xs){
    var i = -1, l = xs.length >>> 0;
    while (++i < l) if (x === xs[i]) return true;
    return false;
  }
}).call(this);
