// Generated by LiveScript 1.3.1
(function(){
  var socket;
  socket = function(app){
    var io;
    io = require('socket.io')(app);
    return io.on('connection', function(socket){
      console.log(io.sockets.sockets.length);
      console.log('connect');
      socket.on('disconnect', function(){
        return console.log('disconnection');
      });
      return socket.on('completion', function(data){
        return console.log('completion');
      });
    });
  };
  module.exports = socket;
}).call(this);
